// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vdias.ExpenseTracker.Models;

namespace Vdias.ExpenseTracker.Main.Migrations
{
    [DbContext(typeof(ExpenseTrackerDBContext))]
    partial class ExpenseTrackerDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Vdias.ExpenseTracker.Models.Expense", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<DateTimeOffset?>("EndDate");

                    b.Property<long>("ExpenseTypeId");

                    b.Property<long>("FrequencyId");

                    b.Property<DateTimeOffset>("StartDate");

                    b.Property<decimal>("Value");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseTypeId");

                    b.HasIndex("FrequencyId");

                    b.ToTable("Expense");
                });

            modelBuilder.Entity("Vdias.ExpenseTracker.Models.ExpenseType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("ExpenseType");
                });

            modelBuilder.Entity("Vdias.ExpenseTracker.Models.Frequency", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("AverageTimesPerMonth");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Frequency");
                });

            modelBuilder.Entity("Vdias.ExpenseTracker.Models.Income", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<DateTimeOffset?>("EndDate");

                    b.Property<long>("FrequencyId");

                    b.Property<DateTimeOffset>("StartDate");

                    b.Property<decimal>("Value");

                    b.HasKey("Id");

                    b.HasIndex("FrequencyId");

                    b.ToTable("Income");
                });

            modelBuilder.Entity("Vdias.ExpenseTracker.Models.Expense", b =>
                {
                    b.HasOne("Vdias.ExpenseTracker.Models.ExpenseType", "ExpenseType")
                        .WithMany()
                        .HasForeignKey("ExpenseTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Vdias.ExpenseTracker.Models.Frequency", "Frequency")
                        .WithMany()
                        .HasForeignKey("FrequencyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Vdias.ExpenseTracker.Models.Income", b =>
                {
                    b.HasOne("Vdias.ExpenseTracker.Models.Frequency", "Frequency")
                        .WithMany()
                        .HasForeignKey("FrequencyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
