// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vdias.ExpenseTracker.Models;

namespace Vdias.ExpenseTracker.Migrations
{
    [DbContext(typeof(ExpenseTrackerDBContext))]
    [Migration("20181102142043_AddExpenseTypeAndExpenseFrequency")]
    partial class AddExpenseTypeAndExpenseFrequency
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Vdias.ExpenseTracker.Models.Expense", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<long>("ExpenseFrequencyId");

                    b.Property<long>("ExpenseTypeId");

                    b.Property<decimal>("Value");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseFrequencyId");

                    b.HasIndex("ExpenseTypeId");

                    b.ToTable("Expense");
                });

            modelBuilder.Entity("Vdias.ExpenseTracker.Models.ExpenseFrequency", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("AverageTimesPerMonth");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("ExpenseFrequency");
                });

            modelBuilder.Entity("Vdias.ExpenseTracker.Models.ExpenseType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("ExpenseType");
                });

            modelBuilder.Entity("Vdias.ExpenseTracker.Models.Expense", b =>
                {
                    b.HasOne("Vdias.ExpenseTracker.Models.ExpenseFrequency", "ExpenseFrequency")
                        .WithMany()
                        .HasForeignKey("ExpenseFrequencyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Vdias.ExpenseTracker.Models.ExpenseType", "ExpenseType")
                        .WithMany()
                        .HasForeignKey("ExpenseTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
