// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Vdias.ExpenseTracker.Migrations
{
    public partial class AddExpenseTypeAndExpenseFrequency : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<long>(
                name: "ExpenseFrequencyId",
                table: "Expense",
                nullable: false);

            migrationBuilder.AddColumn<long>(
                name: "ExpenseTypeId",
                table: "Expense",
                nullable: false);

            migrationBuilder.CreateTable(
                name: "ExpenseFrequency",
                columns: table => new
                {
                    Id = table.Column<long>(nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn),
                    Description = table.Column<string>(nullable: false),
                    AverageTimesPerMonth = table.Column<decimal>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ExpenseFrequency", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "ExpenseType",
                columns: table => new
                {
                    Id = table.Column<long>(nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn),
                    Description = table.Column<string>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ExpenseType", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Expense_ExpenseFrequencyId",
                table: "Expense",
                column: "ExpenseFrequencyId");

            migrationBuilder.CreateIndex(
                name: "IX_Expense_ExpenseTypeId",
                table: "Expense",
                column: "ExpenseTypeId");

            migrationBuilder.AddForeignKey(
                name: "FK_Expense_ExpenseFrequency_ExpenseFrequencyId",
                table: "Expense",
                column: "ExpenseFrequencyId",
                principalTable: "ExpenseFrequency",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_Expense_ExpenseType_ExpenseTypeId",
                table: "Expense",
                column: "ExpenseTypeId",
                principalTable: "ExpenseType",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Expense_ExpenseFrequency_ExpenseFrequencyId",
                table: "Expense");

            migrationBuilder.DropForeignKey(
                name: "FK_Expense_ExpenseType_ExpenseTypeId",
                table: "Expense");

            migrationBuilder.DropTable(
                name: "ExpenseFrequency");

            migrationBuilder.DropTable(
                name: "ExpenseType");

            migrationBuilder.DropIndex(
                name: "IX_Expense_ExpenseFrequencyId",
                table: "Expense");

            migrationBuilder.DropIndex(
                name: "IX_Expense_ExpenseTypeId",
                table: "Expense");

            migrationBuilder.DropColumn(
                name: "ExpenseFrequencyId",
                table: "Expense");

            migrationBuilder.DropColumn(
                name: "ExpenseTypeId",
                table: "Expense");
        }
    }
}
