// <autogenerated />
// Mostly not autogenerated. This flag is here to skip StyleCop analysis.

//-----------------------------------------------------------------------
// <copyright file="Startup.cs" company="Vinicius Dias">
//     All Rights Reserved.
// </copyright>
//-----------------------------------------------------------------------
namespace ExpenseTracker
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Swashbuckle.AspNetCore.Swagger;
    using Microsoft.AspNetCore.Builder;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.HttpsPolicy;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.Extensions.Configuration;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.Extensions.Logging;
    using Microsoft.Extensions.Options;
    using Vdias.ExpenseTracker.Models;

    /// <summary>
    /// Startup class.
    /// </summary>
    public class Startup
    {
        /// <summary>
        /// The major version of the API
        /// </summary>
        private static readonly int API_MAJOR_VERSION = 1;

        /// <summary>
        /// The minor version of the API
        /// </summary>
        private static readonly int API_MINOR_VERSION = 0;

        /// <summary>
        /// The API version as string.
        /// </summary>
        private static readonly string API_VERSION = string.Format("{0}.{1}", API_MAJOR_VERSION, API_MINOR_VERSION);

        /// <summary>
        /// Initializes the Startup class.
        /// </summary>
        /// <param name="configuration">The configuration to be applied.</param>
        public Startup(IConfiguration configuration)
        {
            this.Configuration = configuration;
        }

        /// <summary>
        /// Gets the configuration.
        /// </summary>
        public IConfiguration Configuration { get; }

        /// <summary>
        /// This method gets called by the runtime. Use this method to add services to the container.
        /// </summary>
        /// <param name="services">The service collection.</param>
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);

            this.ConfigureApiVersioning(services);
            this.ConfigureDatabase(services);
            this.ConfigureSwagger(services);
        }

        /// <summary>
        /// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        /// </summary>
        /// <param name="app">The application builder</param>
        /// <param name="env">The hosting environment</param>
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseHsts();
            }

            // applies the migrations
            using (var serviceScope = app.ApplicationServices.GetRequiredService<IServiceScopeFactory>().CreateScope())
            {
                var context = serviceScope.ServiceProvider.GetService<ExpenseTrackerDBContext>();
                context.Database.Migrate();
            }

            app.UseSwagger();
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint(string.Format("/swagger/{0}/swagger.json", API_VERSION), "ExpenseTracker Web API");
            });

            // app.UseHttpsRedirection();
            app.UseMvc();
        }

        /// <summary>
        /// Configures the api versioning.
        /// </summary>
        /// <param name="services">The services collection</param>
        private void ConfigureApiVersioning(IServiceCollection services)
        {
            services.AddApiVersioning(options => options.DefaultApiVersion = new ApiVersion(API_MAJOR_VERSION,
                API_MINOR_VERSION));
        }

        /// <summary>
        /// Configures the database connection and options.
        /// </summary>
        /// <param name="services">The services collection</param>
        private void ConfigureDatabase(IServiceCollection services)
        {
            services.AddEntityFrameworkNpgsql().AddDbContext<ExpenseTrackerDBContext>(options =>
                options.UseNpgsql(Configuration.GetConnectionString("ExpenseTrackerDatabase")));
        }

        /// <summary>
        /// Adds the SWAGGER configuration.
        /// </summary>
        /// <param name="services">The services collection</param>
        private void ConfigureSwagger(IServiceCollection services)
        {
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc(API_VERSION, new Info
                {
                    Title = "ExpenseTracker Web API",
                    Version = API_VERSION
                });
            });
        }
    }
}
